version: '3'

services:
  web:
    image: nginx:1.15
    ports:
      - "80:80"
    volumes:
      - ./samplephpwebsite:/var/www/samplephpwebsite
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links: 
      - php
    depends_on:
      - php
  php:
    image: php:fpm
    volumes:
      - ./samplephpwebsite:/var/www/samplephpwebsite
