version: '3'

services:
  web:
    image: nginx:1.12
    ports:
      - "80:80"
    volumes:
      - ./samplephpwebsite:/var/www/samplephpwebsite
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links: 
      - php
    depends_on:
      - php
  php:
    build: .
    volumes:
      - ./samplephpwebsite:/var/www/samplephpwebsite
    links: 
      - mariadb
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.1
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: php_user
      MYSQL_PASSWORD: sdrugntqqsciur
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
